### ISSUE TITLE
Error on git-Paper-1562 (MC: 1.12.2)

### ISSUE THREAD

**Issue by Eterlzb** [kuohsuanlo/orereplacer#6]
Version: 1.0.1.13.16a4
[13:19:54 ERROR]: Could not pass event BlockBreakEvent to OreReplacerPlugin v1.0.1.13.16a
java.lang.NoClassDefFoundError: Could not initialize class io.github.kuohsuanlo.orereplacer.OreReplacerUtil
at io.github.kuohsuanlo.orereplacer.OreReplacerListener.onBlockBreakEvent(OreReplacerListener.java:118) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor936.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1573]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1573]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1573]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:321) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:124) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:921) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1573]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1573]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1573]

**Comment by kuohsuanlo** [comment]
Current version do not support 1.12

**Comment by kuohsuanlo** [comment]
Latest version does not support 1.12

**Comment by Eterlzb** [comment]
Ok, I will use the old version. Thank for your development.
